spring.application.name=auth-service
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/chili_track
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=auth-service

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET:chilitrack-secret-chilitrack-secret}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
